name: agora_rtc_voice_engine
description: Voice-only Agora RTC Flutter plugin (Android/iOS) — wraps Agora Voice SDKs and exposes audio methods compatible with agora_rtc_engine's audio API.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.danieluwadi.agora_rtc_voice_engine
        pluginClass: AgoraRtcVoiceEnginePlugin
      ios:
        pluginClass: AgoraRtcVoiceEnginePlugin

flutter_api_messages:
  null_safety: true
